repos:
- repo: https://github.com/asottile/reorder-python-imports
  rev: v3.13.0
  hooks:
  - id: reorder-python-imports
- repo: https://github.com/psf/black
  rev: "24.4.2"
  hooks:
  - id: black
- repo: https://github.com/PyCQA/flake8
  rev: "7.1.0"
  hooks:
  - id: flake8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: end-of-file-fixer
  - id: check-json
  - id: check-yaml
    exclude: ^helm-chart/nbviewer/templates/
  - id: check-case-conflict
  - id: check-executables-have-shebangs
ci:
  autofix_prs: false
  autoupdate_schedule: quarterly
